USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS APARTMENT_WATCHER;

USE APARTMENT_WATCHER;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS WAREHOUSE;

CREATE SCHEMA IF NOT EXISTS MARTS;
