--- #### CREATING VIS ROLE
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS VIS_role;
USE ROLE SECURITYADMIN;

--- #### GRANTING ROLES
GRANT ROLE VIS_role TO USER sodahb;
GRANT ROLE VIS_role TO USER jassef;

--- #### WAREHOUSE LAYER GRANTS

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE VIS_role;
GRANT USAGE ON DATABASE APARTMENT_WATCHER TO ROLE VIS_role;
GRANT USAGE ON SCHEMA apartment_watcher.Warehouse TO ROLE VIS_role;
GRANT SELECT ON ALL TABLES IN SCHEMA apartment_watcher.Warehouse TO ROLE VIS_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA apartment_watcher.Warehouse TO ROLE VIS_role;
GRANT SELECT ON ALL VIEWS IN SCHEMA apartment_watcher.Warehouse TO ROLE VIS_role;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA apartment_watcher.Warehouse TO ROLE VIS_role;
GRANT TRUNCATE ON ALL TABLES IN SCHEMA apartment_watcher.WAREHOUSE TO ROLE VIS_role;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA apartment_watcher.WAREHOUSE TO ROLE VIS_role;


--- #### TESTING WAREHOUSE
USE ROLE VIS_role;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE apartment_watcher;

SHOW TABLES IN Warehouse;
SHOW VIEWS IN WAREHOUSE;

--- #### SHOW GRANTS

SHOW GRANTS TO ROLE VIS_role;
SHOW GRANTS ON SCHEMA apartment_watcher.WAREHOUSE;