--- #### DLT ROLE
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS DLT_ROLE;
USE ROLE SECURITYADMIN;

--- #### GRANTING ROLES
GRANT ROLE DLT_ROLE TO USER sodahb;
GRANT ROLE DLT_ROLE TO USER jassef;


--- #### STAGING LAYER GRANTS
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DLT_ROLE;
GRANT USAGE ON DATABASE apartment_watcher TO ROLE DLT_ROLE;
GRANT USAGE ON SCHEMA apartment_watcher.Staging TO ROLE DLT_ROLE;
GRANT CREATE TABLE ON SCHEMA apartment_watcher.Staging TO ROLE DLT_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA apartment_watcher.Staging TO ROLE DLT_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA apartment_watcher.Staging TO ROLE DLT_ROLE;
GRANT TRUNCATE ON ALL TABLES IN SCHEMA apartment_watcher.STAGING TO ROLE DLT_ROLE;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA apartment_watcher.STAGING TO ROLE DLT_ROLE;

--- #### Testing
USE ROLE DLT_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE apartment_watcher;
CREATE TABLE IF NOT EXISTS Staging.test(
    test INTEGER PRIMARY KEY
);
INSERT INTO staging.test (test) 
VALUES(2);

SELECT * FROM staging.test;
DROP TABLE staging.test;


--- #### SHOW GRANTS

USE ROLE SECURITYADMIN;
SHOW GRANTS TO ROLE DLT_ROLE;
SHOW GRANTS ON SCHEMA apartment_watcher.STAGING;
