--- #### DBT ROLE
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS DBT_role;
USE ROLE SECURITYADMIN;

--- #### GRANTING ROLES
GRANT ROLE DBT_role TO USER sodahb;
GRANT ROLE DBT_role TO USER jassef;

--- #### STAGING LAYER GRANTS
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_role;
GRANT USAGE ON DATABASE APARTMENT_WATCHER TO ROLE DBT_role;

GRANT USAGE ON SCHEMA apartment_watcher.staging TO ROLE DBT_role;
GRANT SELECT ON ALL TABLES IN SCHEMA apartment_watcher.STAGING TO ROLE DBT_role;
GRANT SELECT ON ALL VIEWS IN SCHEMA apartment_watcher.STAGING TO ROLE DBT_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA apartment_watcher.STAGING TO ROLE DBT_role;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA apartment_watcher.STAGING TO ROLE DBT_role;

--- #### WAREHOUSE LAYER GRANTS

USE ROLE SECURITYADMIN;

GRANT USAGE ON SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT CREATE TABLE ON SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT CREATE VIEW ON SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL VIEWS IN SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE VIEWS IN SCHEMA apartment_watcher.Warehouse TO ROLE DBT_role;
GRANT TRUNCATE ON ALL TABLES IN SCHEMA apartment_watcher.WAREHOUSE TO ROLE DBT_role;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA apartment_watcher.WAREHOUSE TO ROLE DBT_role;


--- #### TESTING WAREHOUSE
USE ROLE DBT_role;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE apartment_watcher;

CREATE TABLE IF NOT EXISTS Warehouse.test(
    test INTEGER PRIMARY KEY
);
SHOW TABLES IN Warehouse;

INSERT INTO warehouse.test (test) 
VALUES(2);

SELECT * FROM warehouse.test;
DROP TABLE warehouse.test;


--- #### SHOW GRANTS
SHOW GRANTS TO ROLE DBT_role;
SHOW GRANTS ON SCHEMA apartment_watcher.STAGING;
SHOW GRANTS ON SCHEMA apartment_watcher.WAREHOUSE;
SHOW GRANTS ON SCHEMA apartment_watcher.MARTS;