name: Run python script every day at 00.02

on:
  schedule:
    # Run every day at 3:00 AM UTC
    - cron: '2 23 * * *'  

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Processed IDs Artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: processed_ids
          path: ./processed_ids
        continue-on-error: true


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-mac.txt

      # Run the Python script
      - name: Run apartmentads.py script
        env:
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME: ${{ secrets.username }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__PASSWORD: ${{ secrets.password }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__HOST: ${{ secrets.host }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE: ${{ secrets.database }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__SCHEMA: ${{ secrets.schema }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__ROLE: ${{ secrets.role }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__WAREHOUSE: ${{ secrets.warehouse }}

        run: |
          mkdir -p ./processed_ids
          cd setup_dlt
          python apartmentads.py

      - name: Upload Updated Processed IDs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed_ids
          path: ./processed_ids/processed_ids.json
          retention-days: 400
