name: Run python script every day at 00.02

on:
  schedule:
    # Run every day at 3:00 AM UTC
    - cron: '1 23 * * *'  

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'
          
      - name: Install dependencies
        run: |
          cd dlt_setup
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Python script
      - name: Run apartmentads.py script
        env:
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_HOST: ${{ secrets.SNOWFLAKE_HOST }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          cd dlt_setup
          python apartmentads.py
