name: Run python script every day at 00.02

on:
  schedule:
    # Run every day at 3:00 AM UTC
    - cron: '2 23 * * *'  

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      #installing json parser in the runner for the next step
      - name: Install jq
        run: sudo apt-get install jq

      #obtains workflow id from last successful run of this workflow
      - name: Get Latest Workflow Run ID
        id: get-run-id
        run: |
          latest_run_id=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/scheduled-apartment_ads.yml/runs?status=success&per_page=1" \
          | jq -r '.workflow_runs[0].id')
          echo "run-id=$latest_run_id" >> $GITHUB_ENV

    #downloads artifact usin run_id and github token, if it exists, continues if not
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: processed_ids
          path: ./processed_ids
          run-id: ${{ env.latest_run_id }}
          github-token: ${{ secrets.PAT_TOKEN }}

      #checks for existing artifact, creates if it doesn't exist
      - name: Ensure Processed IDs File Exists
        run: |
          mkdir -p ./processed_ids
          if [ ! -f ./processed_ids/processed_ids.json ]; then
            echo "[]" > ./processed_ids/processed_ids.json
          fi
          ls -la ./processed_ids


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-mac.txt

      # Run the Python script
      - name: Run apartmentads.py script
        env:
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME: ${{ secrets.username }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__PASSWORD: ${{ secrets.password }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__HOST: ${{ secrets.host }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE: ${{ secrets.database }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__SCHEMA: ${{ secrets.schema }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__ROLE: ${{ secrets.role }}
          APARTMENTADS__DESTINATION__SNOWFLAKE__CREDENTIALS__WAREHOUSE: ${{ secrets.warehouse }}

        run: |
          mkdir -p ./processed_ids
          python apartmentads_workflow.py

      - name: Upload Updated Processed IDs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed_ids
          path: ./processed_ids/processed_ids.json
          retention-days: 400
