name: Run Compose Email

on:
  push:
    branches:
      - main
  schedule:
    - cron: '2 12 * * *'  
    
jobs:
  run_compose_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run compose_email.py
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          host: ${{ secrets.host }}
          database: ${{ secrets.database }}
          warehouse: ${{ secrets.warehouse }}
          APP_PASSWORD: ${{ secrets.app_password }}
        run: |
          python compose_email_workflow.py
